import { Metadata } from "next";
import GalleryClient from "@/components/GalleryClient";

export const metadata: Metadata = {
  title: "Meme Gallery - Ramadan Meme Generator",
  description: "Browse the funniest Ramadan memes generated by our community. A collection of hilarious 'Mabrouk El Karsh' moments.",
  openGraph: {
    title: "Ramadan Meme Gallery 📚",
    description: "Browse the funniest Ramadan memes generated by our community.",
    url: "https://ramadan-meme-generator.vercel.app/gallery",
    images: [
      {
        url: "/og-gallery.png",
        width: 1200,
        height: 630,
        alt: "Ramadan Meme Gallery Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Ramadan Meme Gallery 📚",
    description: "Browse the funniest Ramadan memes generated by our community.",
    images: ["/twitter-gallery.png"],
  },
};

export default function GalleryPage() {
  return <GalleryClient />;
}
